# Generated by Django 6.0 on 2025-12-16 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorProfile',
        ),
    ]
