# Generated by Django 6.0 on 2025-12-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_deliveryuser_aadhaarphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoruser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendoruser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
