# Generated by Django 6.0 on 2025-12-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_vendoruser_is_active_vendoruser_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendoruser',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
