# Generated by Django 6.0 on 2025-12-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_vendoruser_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoruser',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendoruser',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
